config_version = 1

mappings = [
  ".config/zsh/.zshrc",  # ".config/zsh/.zshenv",  # ".config/zsh/.zpreztorc",
  ".config/zsh/.zlogout",
  ".config/zsh/.zlogin",
  ".config/zsh/.zprezto",
  ".config/zsh/.zpreztorc",
  ".config/zsh/.zshenv",
  ".config/tmux/tmux.conf",
  ".zprofile",
  ".config/git/config",
  ".config/econf",
  ".ssh/config",
  ".config/themes",
  ".xprofile",
  ".profile",
  ".xinitrc",
  ".config/mimeapps.list",
  ".config/zathura",
  ".config/fontconfig",
  ".config/i3blocks",
  ".config/ranger",
  ".config/sxhkd",
  ".config/i3",
  ".local/ricebin",
  ".local/share/applications",
  ".local/share/larbs",
  ".config/dunst/dunstrc",
  ".config/mpd/mpd.conf",
  ".config/mpv",
  ".config/newsboat",
  ".config/sxiv",
  ".config/shell/aliasrc",
  ".config/rofi/scripts",
  ".fonts",
  ".config/nvim",
  ".config/shell/inputrc",
  ".config/systemd",
  ".config/xkb",
  ".config/udevmon_layers",
  ".config/ncmpcpp/config",
  ".config/ncmpcpp/bindings",
  ".spacemacs.d/custom-functions.el",
  ".spacemacs.d/init.el",
  ".config/ideavim/ideavimrc",
  ".config/kitty",
  ".emacs.d/private/snippets",
  ".config/wget/wgetrc",
  ".config/npm",
  ".config/fs-shortcuts",
  ".gdbinit",
  ".config/kittythemechanger.py",
  ".Xresources",
  ".config/arandr",
  ".config/gtk-2.0/gtkrc-2.0",
  ".config/gtk-3.0/settings.ini",
  "srcbin/setup.sh",
  ".config/rofi/config.rasi",
  ".config/picom.conf",
]
