#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman-pkg-install" \
	yay="yay-pkg-install" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

# GIT related shortcuts
alias \
	gf="git fetch" \
	gp="git push" \
	gf="git fetch" \
	gu="git pull" \
	gc="git commit" \
  gm="git checkout main && git pull" \
  gpf="git push --force-with-lease"

# common typos
alias \
	exti=exit

# other tools
alias \
	c="code ." \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
	SS="sudo systemctl" \
	note="emacsclient -t -e '(progn (spacemacs/new-empty-buffer) (org-mode))'" \
	wiki="et $HOME/wiki/" \
	sysrice="sudo yadm -Y /etc/sysrice" \
	la="eza --long --all --header" \
	trello="with-secret-env trello" \
	personal="with-secret-env personal" \
	editmr="with-secret-env forge edit-mr" \
	openmr="with-secret-env forge open-mr" \
	createissue="with-secret-env forge create-issue -o" \
	ssh="TERM=xterm-color ssh" \
	kitty="kitty --single-instance" \
	theme="kitty-theme --config ~/.config/kittythemechanger.py" \
	toggle-theme="theme -t && theme -L" \
	dark="change-theme dark" \
	light="change-theme light" \
  npr="npm run" \
  agenda="et -t --eval '(org-agenda-list)' '(delete-other-windows)'" \
  protocol="et ~/GoogleDrive/Documents/Schule/ETH/Bsc-Thesis/Meetings/meetings.org" \
  thesis-notes="et ~/GoogleDrive/Documents/Schule/ETH/Bsc-Thesis/notes/notes.org"

# environment specific aliases
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"
[ -x "$(command -v xdg-open)" ] && alias open="xdg-open"
[ -x "$(command -v xclip)" ] && alias copy="xclip -selection -c" paste="xclip -selection c -o"
[ -x "$(command -v pbcopy)" ] && alias copy="pbcopy" paste="pbpaste"
[ -x "$(command -v exa)" ] && alias la="exa --long --all --header"
# [ -x "$(command -v trash)" ] && alias trash-put="trash"
