#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# This file's true location is in ~/.config/xprofile and a link exists to it in
# ~/.xprofile. If you do not use a DM, you may remove the link to it to have a
# cleaner home.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

autorandr -c # load first detected xrandr profile

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # required for authentication requests such as 1password
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

# Start deskop environment:
/usr/bin/xfce4-panel &
/usr/bin/xfsettingsd &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
xfce4-power-manager &

# start user daemons which are not managed by systemd:
systemctl --user start kmonad     # start kmonad manually here to make sure X11 is alrady running
playerctld daemon                 # run playerclt daemon in background to track last recently used media player
nitrogen --restore                # restore the last used desktop background image
picom &                           # window compositor supporting transparency
unclutter &                       # Remove mouse when idle
sxhkd &                           # Bind keys
nm-applet &                       # network sys-tray
blueman-applet &                  # bluetooth sys-tray
dex -a -s $HOME/.config/autostart # auto start user specific apps
kdeconnect-indicator &            # KDE connect systray icon

# Trackpad
# synclient TapButton1=1 # enable tap to click
# should already be configured in 70-synaptics.conf
# synclient PalmDetect=1 # enable palm detection

# load theme: merge normalize after actual theme:
xrdb $HOME/.config/themes/normalize.xresource
xrdb -merge $HOME/.config/themes/Argonout.xresource
