#!/usr/bin/env bash

if [[ "$#" -eq 0 ]]; then
    mkdir -p /tmp/c-repl
    dir=$(mktemp -d -p /tmp/c-repl/)
else
    dir="$1"
fi

pushd $dir
if [[ ! -f main.c ]]; then
    echo -e "#include <stdio.h>\n\nint main() {\n\treturn 0;\n}" >> main.c
fi

start-terminal -e sh -c "cd $dir && echo main.c | entr -c sh -c 'gcc -g main.c -o main.out && ./main.out'" &
code -n $dir/main.c
popd
