#!/usr/bin/env sh

if [ $# -eq 1 ]; then
	echo $1 | entr -crp sh -c 'g++ -g -O0 main.cpp -o main && ./main'
else
	mkdir -p /tmp/cpp-repl
	dir=$(mktemp -d -p /tmp/cpp-repl/)
	pushd $dir
	echo -e "#include <iostream>\nusing namespace std;\n\nint main() {\n\treturn 0;\n}" >>main.cpp
	start-terminal -e sh -c "cd $dir && cpp-repl main.cpp" &
	code -n $dir
	popd
fi
