#!/usr/bin/env sh

uptime=$(uptime -p | sed -e 's/up //g')

lock="lock"
logout="logout"
hibernate="hibernate"
suspend="suspend"
reboot="reboot"
poweroff="poweroff"

options="\
🔒 $lock
👋 $logout
🐻 $hibernate
😴 $suspend
🔃 $reboot
🚪 $poweroff"

choice=$(echo -e "$options" | rofi -width 22 -columns 6 -lines 1 -p "Uptime: $uptime" -dmenu -selected-row 2)

case $(echo "$choice" | cut -d' ' -f2-) in
    $poweroff)
        systemctl poweroff
        exit 0
        ;;
    $reboot)
        systemctl reboot
        exit 0
        ;;
    $lock)
        lock-screen &
        exit 0
        ;;
    $logout)
        i3-msg exit
        exit 0
        ;;
    $hibernate)
        systemctl hibernate
        exit 0
        ;;
    $suspend)
        systemctl suspend
        exit 0
        ;;
esac
