#!/bin/sh

# Open a terminal window in the same directory as the currently active window.

PID=$(xprop -id "$(xprop -root | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{print $NF}')" | grep -m 1 PID | cut -d " " -f 3)
PID="$(pstree -lpA "$PID" | head -n 1 | sed 's/^.*'"$(basename $SHELL)"'(\([0-9]*\)).*$/\1/')"
cd "$(readlink /proc/"$PID"/cwd)" || return 1
"$TERMINAL"
