#!/usr/bin/env sh

# Simple script used as $TERMINAL.
# spawns a new terminal with custom args additionally to all given arguments:

# kitty --single-instance "$@"
# kitty "$@"

if [[ "$#" -eq 0 ]]; then
    alacritty -e tmux
else
    alacritty "$@"
fi

