#!/usr/bin/env bash

#
# Executes a command with its arguments in an environment
# where the GNU pass entry with the command's name was sourced before.
# The GNU pass entry is sourced - make sure you trust your credentials and export everythin you need!
#
# This allows eg. saving credentials as environment variables in a pass entry
# and start the desired command via this script:
# // ~/.password-store/my-command.gpg:
# export MY_VAR=foo # export is important!
#
# // my-command:
# echo $MY_VAR $1
#
# // prints 'foo bar':
# with-secure-env my-command bar
#
# The name/path of the pass file to source can be overwritten using the
# environemt variable WITH_SECRET_ENV_FILE. Its value is directly forwarded
# to `pass show'.
#

if [[ $# -eq 0 ]]; then
    echo "invalid arguments. Usage: [WITH_SECRET_ENV_FILE=<pass_file>] with-secret-env <EXEC> [..EXEC_ARGS]"
    exit 1
fi

exec_path=$1
file_name=${WITH_SECRET_ENV_FILE:-$(basename $1)}

source <(pass show $file_name)
exec $exec_path "${@:2}" 
