#!/bin/sh
xrandr --output eDP-1-1 --mode 2560x1440 --pos 635x2174 --rotate normal --output DP-1-1 --off --output HDMI-1-1 --off --output DP-1-2 --off --output HDMI-1-2 --mode 3840x2160 --pos 0x0 --rotate normal
