#!/bin/sh
xrandr --output eDP-1 --primary --mode 2560x1440 --pos 388x1440 --rotate normal --output DP-1 --mode 3440x1440 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --off
