#!/usr/bin/env sh

# by default: shows a notification bubble with all packages ready to update
# if flag -c is provided, it writes the number up outdated packages to stdout
if [ "$1" == "-c" ]; then
    /usr/bin/pacman -Qu | wc -l
else
    notify-send $(/usr/bin/pacman -Qu)
fi
